-- Sync missing columns (safe: IF NOT EXISTS / backfill)
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "rc" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "taxId" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'Maroc';

ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "reference" TEXT;
UPDATE "Purchase" SET "reference" = 'ACH-LEGACY-' || LEFT("id", 8) WHERE "reference" IS NULL OR "reference" = '';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Purchase_reference_key'
  ) THEN
    ALTER TABLE "Purchase" ADD CONSTRAINT "Purchase_reference_key" UNIQUE ("reference");
  END IF;
END $$;

ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "invoiceNumber" TEXT;
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "invoiceDate" TIMESTAMP(3);
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "purchaseType" TEXT DEFAULT 'LOCAL';
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'MAD';
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "amountHT" DECIMAL(14,2) DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "taxAmount" DECIMAL(14,2) DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "amountTTC" DECIMAL(14,2) DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "discount" DECIMAL(14,2) DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "totalPurchasePrice" DECIMAL(14,2) DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "totalExpenses" DECIMAL(14,2) DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "costPrice" DECIMAL(14,2) DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "paymentStatus" TEXT DEFAULT 'UNPAID';
ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'DRAFT';

ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "firstRegistrationDate" TIMESTAMP(3);
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "interiorColor" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "fiscalPower" INTEGER;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "engineSize" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "originCountry" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "vehicleCondition" TEXT;

ALTER TABLE "PurchaseFee" ADD COLUMN IF NOT EXISTS "expenseDate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "supplierId" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "bank" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "checkNumber" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP(3);

ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "paymentId" TEXT;

ALTER TABLE "StockMovement" ADD COLUMN IF NOT EXISTS "movementType" TEXT DEFAULT 'INITIAL';
ALTER TABLE "StockMovement" ADD COLUMN IF NOT EXISTS "purchaseId" TEXT;
ALTER TABLE "StockMovement" ADD COLUMN IF NOT EXISTS "movementDate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
